### PR TITLE
Removed compromised website links

### PR DESCRIPTION
**Pull request by Jahhein**
README.md and index.md had two links pointing to compromised websites.

Per request on https://github.com/iluwatar/java-design-patterns/issues/577 I have fixed the links here on the repository.

---
This change is [Reviewable](https://reviewable.io/reviews/webpro/programming-principles/24)

### CODE REVIEW

**Comment by webpro** [comment]
Thanks, @Jahhein. Any chance you could replace the links with quality alternatives where available?,

**Comment by Jahhein** [comment]
I'm sorry I do not at the moment. As I gain more knowledge through helping the java-design-patterns repository, perhaps I will find some. Any suggestions on where a great place to begin my search would be?

**Comment by webpro** [comment]
OK, these links should be removed in any case, so thanks!

As for your question: Google? ;-)

**Comment by Jahhein** [comment]
I meant other than the usual google. 👍 

Thanks for the merge, was just as I pushed for the replacement links. Ha!

**Pull request merged**
